apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g4u1cqarx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g4u1cqarx-nodejs 
  name: g4u1cqarx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: g4u1cqarx-nodejs 
